create_site: 'create.extension.org'
articles_site: 'articles.extension.org'
urlwriter_host: 'imageaudit.extension.org'
app_location: 'production'
honeybadger_api_key: 'use_local_settings'
session_token: '123456789012345678901234567890'
# mysql group concat size for percentiles
group_concat_max_len: 1048576
drupal_file_source_path: '/services/nfs/drupalfiles/files'
slack_webhook: 'use_local_settings'
default_slack_channel: "use_local_settings"
imageaudit_slack_channel: 'use_local_settings'
sidekiq_enabled: true
